name: Build and Deploy Docker Image

on:
  push:
    tags:
      - "*.*.*" # stable semantic versions
      - "*.*.*-*" # pre-release versions (beta, rc, etc.)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker build \
            --platform linux/amd64,linux/arm64 \
            -t tskiba/requira:latest \
            -t tskiba/requira:$VERSION \
            .

      - name: Push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker push tskiba/requira:latest
          docker push tskiba/requira:$VERSION
